### ISSUE TITLE
Support for AUTOCOMMIT

### ISSUE THREAD

**Issue by pca2** [camilo/sequel-vertica#13]
By default Vertica has sets [AUTOCOMMIT](http://my.vertica.com/docs/4.1/HTML/Master/12149.htm) to false. Is it possible to edit this setting with sequel-vertica? By [default Sequel is supposed to have AUTOCOMMIT on](http://sequel.jeremyevans.net/rdoc/files/doc/transactions_rdoc.html), but in my testing it doesn't appear to be the case. You can always run raw sequel `DB.run('set session autocommit to on')` but it'd be better if that wasn't the only option

**Comment by wvanbergen** [comment]
We're not actively using this gem anymore; if you want this fixed I suggest you fork it and implement it yourself.
